---
title: "Introduction"
author: "Amieroh Abrahams"
date: "3 July 2018"
output: html_document
  word_document:
    toc: yes
  html_document:
    fig_caption: yes
    fig_height: 5
    fig_width: 5
    highlight: default
    number_sections: yes
    theme: paper
    toc: yes
    toc_float: yes
  pdf_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 6
    highlight: zenburn
    latex_engine: xelatex
mainfont: PT Serif
monofont: PT Mono
language: Australian
sansfont: PT Sans
fontsize: 12pt
---

# Introduction

Temperature is the main determinant of biogeographical patterns and ecosystem processes, having observable effects on an organism’s survival and reproductive patterns (Smit et al. 2013). Temperature is also a key indicator of marine environmental change (Pearce et al. 2006). Despite the controlling effect that temperature plays on the growth, survival, and distributions of marine organisms, little is known in regarding temperatures within coastal zones. Within the coastal zone, temperature is affected by a range of nearshore processes such as wave action, tides, and turbidity. Additionally, the thermal properties of the substratum may also affect temperature variation (Smale and Wernberg 2009) and so there is a large scope for variation at the localized scale. Given the importance of the impacts of temperature, there is a need to understand how marine organisms may respond to temperature variation at coastal regions at both the global and local scale.

The South African coastal environment, which spans a length of approximately 3113 km, is one such region where little is known about localized coastal temperatures. This region exhibits a large variation in seawater temperatures across its coastline (Mead et al. 2013; Smit et al. 2013) and is divided into three coastal provinces. These provinces are the cold temperate West coast, warm temperate South coast, and the subtropical East coast. Each of these provinces has been found to display noticeable differences in seawater temperatures in comparison to each other, and also differ in terms of their biodiversity (Bolton et al. 2004; Mead et al. 2013; Smit et al. 2013; Schlegel and Smit 2016). These observed differencesbetween coasts are primarily due to the unique oceanic conditions associated with the geographical position of South Africa.

Variation in seawater temperature around the coastline of South Africa is largely due to this region being influenced by both the Agulhas and Benguela currents, which together are responsible for the presence of a strong West-East thermal gradient occurring along this coastal zone (Smit et al. 2013). Such are the impacts of these that they largely influence regional weather patterns and climate of the marine environment (Rouault et al. 2009) via an exhibition of a consistent downstream circulation feature which results in the presence of cool temperate waters along the western province of the coastline (Lutjeharms and Ballegooyen 1988). Conversely, the Agulhus current, in the form of western boundary current, transports sub-tropical, warm waters towards the tip of Africa thus resulting in the eastern province having much warmer seawater (Smit et al. 2017). Differences in seawater temperatures between these currents along the South African coastline have been found to vary statistically.

 The statistical properties such as the mean, minimum, and maximum temperatures of in situ coastal seawater temperature time series representing the entire South African coastline show distinct coastal variations as a result of the Agulhas and Benguela currents (Schlegel and Smit 2016). Due to the small range of ambient temperatures experienced on the West coast, fluctuations are able to occur over a short period of time. Furthermore, research suggests that the temperatures of these regions are changing in recent years (Schlegel and Smit 2016), with increases of between 0.558 – 0.78 °C decade-1 in the Agulhas Current and a 0.58 °C decade-1 increase in the southern Benguela current (Rouault et al. 2009; 2010). These increases in temperature could have profound effects on marine organism within these regions, but before we can quantify those we first need to quantify current seawater temperature trends. 
 
Over the last few decades, improvements in remote sensing technology have enabled researchers to map global sea surface temperature with a higher level of accuracy (Zainuddin et al. 2006; Smale and Wernberg 2009). In this way, sea surface temperatures (SST) are obtained across large or remote areas by means of satellite remote sensing (Pearce et al., 2005). The National Oceanic and Atmospheric Administration (NOAA) series of satellites have provided global SSTs for more than two decades at both global and local scales (Pearce et al. 2005). These data are critically important as satellite temperature datasets are often used to monitor changes in ocean temperatures and provide valuable information on both biological and physical parameters in the ocean (Demarcq et al. 2010). Furthermore, satellite-derived SST data plays an important role in the creation of projections for the potential effects of climate change on coastal and oceanic marine biota (Muller et al. 2009; Hilbish at al. 2011; Bartsch et al. 2012). Recently, in areas where nearshore coastal water temperature data is scarce, particularly within a couple of pixels of the coastline, the use of satellite-derived seawater temperature as a proxy for deriving water temperature along the coastal zone has gained in popularity (Smale and Wernberg 2009) despite these data being unreliable. 

Developments in in situ collected coastal sea water temperature data products over the last three decades provide a more reliable source of obtaining coastal seawater temperature data (Smit et al. 2013). The South African Coastal Temperature Network (SACTN) has collected SST data for the South African coastline from as early as 1972, with contributions from various organisations and governmental departments. This data was obtained via a combination of different instruments and methods, such as via hand held alcohol thermometers and underwater temperature recorders, and as a result of this disparity the SST data has been recorded at differing levels of precision (0.5°C versus 0.001°C) but are likely as or more reliable than satellite derived data. 

Satellite-derived temperature measurements often differ from in situ measurements (Katsaros 2003; Castillo and Lima 2010). This is primarily due to coastal satellite measurements failing to record small-scale variability or provide realistic information on mean climatological temperatures. Smit et al. (2013) have shown that within offshore environments satellite data generally reflects reality and have been validated against in situ measurements. At coastal regions however they found that satellite-derived data have a warm bias of 6 °C when compared to coastal in situ collected seawater temperature data. For study sites located within a 400 m distance of the shoreline, it is recommended that data collected in situ be used over satellite-derived temperatures where possible (Smit et al. 2013).

The purpose of this paper is to quantify temperature variation between selected sites along the South African coastline in order to determine how marine organisms may be affected by temperature fluctuations along this region. Additionally, this paper also looks to examine the influence of environmental factors, namely, wave action and exposure on coastal seawater temperatures. The aims of this study are to: i) examine whether there is homogeneity between the various sites sampled, ii) examine the driving factors that cause variation in coastal seawater temperatures along the South African coastline and iii) to examine whether the different instruments used in this study had an effect on the variation in temperature. These aims will be achieved by examining the wave and coastal seawater temperature datasets in order to test the amount of variability between the sites located along the coast.

# Methods

## Study area

The South African coastline spans ~3100 km providing a large area for temperature recordings via satellite and *in situ* measurements needed for the study (Schlegel and Smit 2016). Bordered by the Benguela and Agulhas Current, the west coast of South Africa differs from the other two coasts in that it forms part of an Eastern Boundary Upwelling System, whilst the east coast is dominated by the western boundary Agulhus current (Hutchings et al 2009; Schlegel et al., 2017). The south coast, also bordered by the Agulhas Current, differs from the east coast as it experiences both shear-forced and wind driven upwelling (Lutjeharms et al. 2000; Schlegel et al., 2017). In order to compare the temperature variation between the sites along the coast, datasets for both temperature and wave action were analyzed.

Wave action and exposure were important variables in this study as they exhibit a direct influence on coastal temperature. Existing thermal and wave energy data for all sites were analyzed in order to investigate the impact of abiotic parameters on seawater temperature at specific sites along the South African coast. Previous studies suggest that ocean temperatures located in these regions, analyzed in the study, are constantly changing (Rouault et al. 2009). This is evident as an increase in seawater temperature along the Agulhas Current and a decrease in seawater temperature along the southern Benguela Current has been recently reported (Rouault et al. 2009; 2010; Schlegel and Smit 2016).

## Data

### Temperatures

The SACTN temperature dataset was compiled by measuring coastal seawater temperatures at 135 sites along the coast of South Africa, daily from 1972 until 2017. Temperatures were measured either manually using hand-held thermometers or electronically using underwater temperature recorders (UTRs). Of the 135 sites, 87 were measured using the thermometers and the remaining 48 were measured using UTRs. Predominantly along the east coast of South Africa data was collected using glass thermometers from boats at the shark net locations along the coastline. Both alcohol and glass thermometers allows for a precision of 0.1°C, the recordings are recorded at 0.5°C. Seven sources contributed towards the compilation of this dataset; The Department of Environmental Affairs (DEA), South African Weather Services (SAWS), University of the Western Cape (UWC), Department of Forestry and Fisheries (DAFF), Kwa Zulu Natal Sharks Board (KZNSB), South African Environmental Observation Network (SAEON) and Ezemvelo KZN Wildlife Organization (EKZNW). KZNSB and SAWS made use of hand-held alcohol thermometers, and took measurements 20 cm below the sea surface. DEA, DAFF, SAEON, UWC and EKZN used the UTRs to obtain seawater temperature recordings at each of the sites. Electronic instruments used for seawater temperature recordings has improved over the past four decades. Previously used Onset Hobo UTR collected seawater temperature at  a precision of 0.01°C, currently used Starmon Mini UTR collect temperature at a thermal precision of 0.001°C. The temperature data that are manually recorded using thermometers are saved a distinct location of the respecitive organizations or govermental departments. Divers install and service the UTR devices every eight months and temperature data extractions occurs annually. This digital data is then downloaded at saved at the head offices of the respective organisations and govermental departments. 

### Waves

Wave energy data formed part of the South African Coastal Vulnerability Assessment, presented to the DEA (Theron et al. 2014). The data were calculated using NOAA Wave Watch III (WWIII) in association with the National Centers for Environmental Predictions (NCEP) products as the numerical input (Benassai and Ascione 2006). Hindcast data from WWIII ranged from 1994-2013 at a 3-hour resolution. The data were then used to model short crested waves generated by the wind into the coastal environment, using Simulating Waves in the Nearshore (SWAN) (Booij et al. 1997). The SWAN model allows one to extract wave parameters from a specific location along the coastal nearshore environment.

