---
title: "Quantifying the impacts of physical factors on the ocean temperatures along the South African coastal system"
author: "Amieroh Abrahams"
date: "30 March 2018"
output:
  word_document:
    toc: yes
  html_document:
    fig_caption: yes
    fig_height: 5
    fig_width: 5
    highlight: default
    number_sections: yes
    theme: paper
    toc: yes
    toc_float: yes
  pdf_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 6
    highlight: zenburn
    latex_engine: xelatex
mainfont: PT Serif
monofont: PT Mono
language: Australian
sansfont: PT Sans
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage
# Introduction

Temperature is the main determinant of biogeographical patterns and ecosystem processes, having observable effects on an organism’s survival as well as their reproductive patterns (Smit et al. 2013). Despite the important role that temperature plays on the terrestrial and marine environment, little is known in regards to the effect of environmental factors as well as the variation across coastal seawater temperatures (Smale and Wernberg 2009). Temperature is affected by a range processes that occur nearshore. A thorough understanding of these coastal processes is provided by a number of physical variables.

The seawater temperatures found around South Africa’s coastline exhibits a large variational range. The coastal region is divided into three provinces, namely the cold temperate west coast, warm temperate south coast and the subtropical east coast (Schlegel and Smit 2016; Smit et al 2013; Mead et al 2013). The Agulhas and Benguela currents, are the two currents that influence the oceans surrounding South Africa. These two adjacent currents create a strong thermal gradient along the shores of South Africa and can vary up to 10°C on any given day, creating the observed fluctuations in seawater temperature (RWS: CItation? THis is news to me.). The Benguela Marine Province (BMP) is located to the west of Cape Point and is characterized by the movement of cold water from the Southern Ocean moving north. The cold temperate west coast mentioned above is greatly affected by the upwelling caused by offshore winds, generated by the cold Benguela current (RWS: citation). Due to the small range of ambient temperatures experienced on the west coast, fluctuations are able to occur over a short period of time (RWS: citation). Research suggests that the temperature of these regions are changing in recent years (Schlegel and Smit 2016). This is evident by an increase of 0.558–0.78°C decade-1 in the Agulhas Current (Rouault et al. 2009; 2010) and a 0.58°C decade-1 increase in the southern Benguela current during the year (Rouault et al. 2010).

The Agulhas Current is considered to be the strongest western boundary current, globally, producing meanders that expel continual eddies into regions including the Agulhas Retroflection and Cape Basin (RWS: citation). The Agulhas Bank Ecoregion located to the east of Cape Point, makes up the western half of the Agulhas Province, which is governed by the warm Agulhas Current that flows south along the east coast of South Africa (RWS: citation). The Agulhas current serves as the trigger of a potential climate feedback mechanism (RWS: citation). Eddies, fronts, and filaments influenced by the Agulhas Current are vast, both quantitatively as well as spatially, exhibiting sharp horizontal sea surface temperature (SST) gradients (RWS: citation). These gradients have a great impact on air and sea thermodynamics, in both a local and regional capacity (RWS: citation).

On a global scale, ocean thermal regimes are maintained by currents as well as latitudinal solar heat flux gradients (RWS: citation). On a local scale (<10 km), at the land/sea margin, additional unfamiliar physical phenomena contribute to the thermal patterns and dynamics, differing from those on a mesoscale (i.e., spatial scales > 50 km) (Smit et al. 2017). The properties of the temperature regime, responsible for setting up biogeographical patterns are less understood in this region, specifically at regional and local scales, in close proximity to land where satellite data poorly reflects reality (Smit et al. 2013). Due to these inconsistencies, annual mean temperatures are often used in cases where temperature is recognised as a major driver of species distribution (RWS: citation). Satellite derived data is often consulted as the source of these annual mean temperatures (Smit et al. 2017).

Over the last few decades, improvements in remote sensing technology have enabled researchers to map global sea surface temperature (SST) with a higher level of accuracy (Smale and Thomas Wernberg 2009). This is important as satellite temperature datasets are often used to monitor changes in ocean temperatures. Satellite-derived SST data plays an important role in the creation of projections for the potential effects of climate change on coastal and oceanic marine biota (Bartsch et al. 2012; Muller et al. 2009; Hilbish at al. 2011). There has been a development in *in situ* collected coastal sea water temperature data products over the last three decades (Smit et al. 2013), used by the South African Coastal Temperature Network (SACTN), as early as 1972. In some regions the temperature records contained in these diverse datasets have been validated against precise in situ temperature measurements (Smit et al. 2013), true for offshore regions where satellite data generally reflects reality. Satellite-derived temperature measurements can often differ from in situ measurements (Castillo and Lima 2010; Katsaros 2003), as coastal satellite measurements often fail to record small-scale variability or provide realistic information on mean climatological temperatures (Smit et al. 2013). For study sites located within a 400m distance of the shoreline, it is recommended that data collected *in situ* be used over satellite-derived temperatures where possible (Smit et al. 2013).

The purpose of this paper is to examine the temperature variation observed between a number of different sites located along the South African coastline as well as to examine the influence of environmental factors, namely, wave action and exposure on costal seawater temperatures. The aims of this study are to; i) examine whether there is homogeneity between the various sites sampled, ii) examine the driving factors that cause variation in coastal seawater temperatures along the South African coastline and iii) to examine whether the different instruments used in this study had an effect on the variation in temperature. These aims will be achieved by examining the wave and coastal seawater temperature datasets in order to test the amount of variability between the sites located along the coast.


# Methods

## Study area

The South African coastline spans ~3100 km providing a large area for temperature recordings via satellite and *in situ* measurements needed for the study (Schlegel and Smit 2016). Bordered by the Benguela and Agulhas Current, the west coast of South Africa differs from the other two coasts in that it is part of an Eastern Boundary Upwelling System, whilst the east coast is dominated by the western boundary Agulhus current (RWS: citation). The south coast, also bordered by the Agulhas Current, differs from the east coast as it experiences both shear-forced and wind driven upwelling (RWS: citation). In order to compare the temperature variation between the sites along the coast, datasets for both temperature and wave action were analyzed.

Wave action and exposure were important variables in this study as they exhibit a direct influence on coastal temperature (RWS: citation). Wave action encompasses a number of specific parameters including wave height, direction and period, of which, not much information regarding their influence on temperatures is known as sites are either exposed or sheltered from wave action (RWS: What relevance does this have?). Existing thermal and wave energy data for all sites were analyzed in order to investigate the impact of abiotic parameters on seawater temperature at specific sites along the South African coast. Previous studies suggest that ocean temperatures located in these regions, analyzed in the study, are constantly changing (RWS: citation). This is evident as an increase in seawater temperature along the Agulhas Current and a decrease in seawater temperature along the southern Benguela Current has been recently reported (RWS: citation).

## Data

### Temperatures

The SACTN temperature dataset was compiled by measuring coastal temperatures at 135 sites along the coast of South Africa, daily from 1972 until 2017. Temperatures were measured either manually using hand-held thermometers or electronically using underwater temperature recorders (UTRs). Of the 135 sites, 87 were measured using the thermometers and the remaining 48 were measured using UTRs. Seven sources contributed towards the compilation of this dataset; The Department of Environmental Affairs (DEA), South African Weather Services (SAWS), University of the Western Cape (UWC), Department of Forestry and Fisheries (DAFF), Kwa Zulu Natal Sharks Board (KZNSB), South African Environmental Observation Network (SAEON) and Ezemvelo KZN Wildlife Organization (EKZNW). KZNSB and SAWS made use of hand-held alcohol thermometers, and took measurements 20 cm below the sea surface. DEA, DAFF and EKZN used the UTRs, attaching them at depths of 4 m to 9 m (RWS: Check these numbers.). SAEON data were collected at a depth of 3 m (RWS: Not always. Check the meta-data.) whilst UWC data were collected at a depth of 1m (RWS: Also no. Check the meta-data.), both using UTRs. Thermometers and UTRs were the preferred choice of equipment as satellite SST is regarded as unreliable in terms of measuring coastal sea water temperature (Smit et al. 2013). The thermometers used in this study were precise to 0.5°C, and the UTR devices used were precise to 0.001°C.

### Waves

Wave energy data formed part of the South African Coastal Vulnerability Assessment, presented to the DEA (Theron et al. 2014). The data were calculated using NOAA Wave Watch III (WWIII) in association with the National Centers for Environmental Predictions (NCEP) products as the numerical input (Benassai and Ascione 2006). Hindcast data from WWIII ranged from 1994-2013 at a 3-hour resolution. The data were then used to model short crested waves generated by the wind into the coastal environment, using Simulating Waves in the Nearshore (SWAN) (Booij et al. 1997). The SWAN model allows one to extract wave parameters from a specific location along the coastal nearshore environment.


## Statistical analysis

Redundancy Analyses (RDA) were performed to examine the impact of environmental drivers on the coastal seawater temperature. The RDA allows one to calculate the amount of variation in response variables as explained for by explanatory variables. Multiple regressions were performed to compare the differences between variables, these variables being the physical factors that affected temperature. Pairwise correlations were plotted to test whether wave and temperature parameters correlated with one another. Therefore fluctuations in the mean, minimum and maximum values were included as temperature parameters.


## References

Bartsch I, Wiencke C and Laepple T. 2012. Global Seaweed Biogeography Under a Changing Climate: The Prospected Effects of Temperature. In: Wiencke C, Bischof K, editors. Seaweed Biology. Ecological Studies. Berlin, Heidelberg: Springer Berlin Heidelberg 219: 383–406.

Benassai, G. and Ascione, I. 2006. Implementation and validation of wave watch iii model offshore the coastlines of southern italy. Proceedings of 25th international conference on offshore mechanics and arctic engineering 92555: 553–560.

Booij, N. et al. 1997. The“ swan” wave model for shallow water. Coastal engineering 1996. pp.668–676.

Castillo K. D and Lima F. P. 2010. Comparison of in situ and satellite-derived (MODIS-Aqua/Terra) methods for assessing temperatures on coral reefs. Limnology and Oceanography Methods 8: 107–117.

Katsaros, K. B .2003. Satellite Versus In Situ Measurements at the Air-Sea Interface. In: Potter TD, Colman BR, editors. Handbook of Weather, Climate, and Water: Dynamics, Climate, Physical Meteorology, Weather Systems, and Measurements.

Theron, A. et al. 2014. MetOcean Conditions & Vulnerability – Medium resolution wave climate & run-up. South African Coastal Vulnerability Assessment DEA - CSIR: Phase 2. Report delivered to Department Environmental Affairs, South Africa.

Hilbish, T. J. et al. 2011. Change and stasis in marine hybrid zones in response to climate warming. Journal of Biogeography 39: 676–687.

Rouault M, Pohl B, and Penven, P. 2009. Warming in the Agulhas Current system since the 1980’s. Geophys. Res. Lett., 36,L12602,.

Rouault M, Pohl B, and Penven, P. 2010. Coastal oceanic climate change and variability from 1982 to 2009 around South Africa. Geographica; research letters 32: 237–246.

Schlegel, R. W and Smit, A. J. 2016. Climate Change in Coastal Waters: Time Series Properties Affecting Trend Estimation. Journal of Climate 29: 9113-9124.

Smale D. A, Wernberg T. 2009. Satellite-derived SST data as a proxy for water temperature in nearshore benthic ecology Peer reviewed article. Marine Ecology Progress Series 387: 27–37.

Smit, A. J. et al. 2013. A coastal seawater temperature dataset for biogeographical studies: large biases between *in situ* and remotely-sensed data sets around the coast of South Africa. PLOS ONE 8: e81944.

Smit, A.J. et al. 2017. Seaweeds in Two Oceans:Beta-Diversity. Frontiers in Marine Science 4: 1-15.

Mead, A., and Coauthors, 2013: Human-mediated drivers of change—Impacts on coastal ecosystems and marine biota. African Journal of Marine Science 35: 403–425

Muller R, Laepple T, Bartsch I and Wiencke C. 2009. Impact of oceanic warming on the distribution of seaweeds in polar and cold-temperate waters. Botanica Marina 52: 617–638.
