---
title: "Acknowledgements"
author: "Amieroh Abrahams"
date: "11 August 2018"
output: html_document
---

Acknowledgments

Special thanks go to my supervisor, AJ Smit, for the continuous motivation and guidance throughout my honours year. All of your contributions and efforts towards my academic career and experiences have been appreciated beyond measure. I would also like to thank my co-supervisor, Dr. Robert Williamson and Dr. Robert Schlegel for the help with R. I would like to thank KZNSB, DEA, DAFF, SAEON and EKZNW for contributing the raw data allowing me to do this study. Without the data this thesis would not be possible.I would also like to thank my colleagues within Team Kelp who assisted me throughout this project. Their discussions, friendships has largely aided in the completion of this thesis. To my friends and family, thank you for providing me with the necessary support and encouragement. I would like to acknowledge the entire Biodiversity and Conservation biology department at the University of the Western Cape. Lastly, i would like to thank the NRF for providing the necessary funding towards the completion of this project.



