---
title: "Complete"
author: "Amieroh Abrahams"
date: "11 August 2018"
output: html_document
---
\newpage
## Plagiarism Declaration


\newpage
## Declaration


\newpage
## Abstract


\newpage
## Acknowledgments

Special thanks go to my supervisor, AJ Smit, for the continuous motivation and guidance throughout my honours year. All of your contributions and efforts towards my academic career and experiences have been appreciated beyond measure. I would also like to thank my co-supervisor, Dr. Robert Williamson and Dr. Robert Schlegel for the help with R. I would like to thank KZNSB, DEA, DAFF, SAEON, SAWS, UWC and EKZNW for contributing the raw data allowing me to do this study. Without the data this thesis would not be possible.I would also like to thank my colleagues within Team Kelp who assisted me throughout this project. Their discussions, friendships has largely aided in the completion of this thesis. To my friends and family, thank you for providing me with the necessary support and encouragement. I would like to acknowledge the entire Biodiversity and Conservation biology department at the University of the Western Cape. Lastly, i would like to thank the NRF for providing the necessary funding towards the completion of this project.

\newpage
# Introduction

Temperature is the main determinant of biogeographical patterns and ecosystem processes, having observable effects on an organism’s survival and reproductive patterns (Smit et al. 2013). The temperatures of seawater are a key indicator of environmental changes in marine ecosystems (Pearce et al. 2006). Despite the controlling effects that temperature plays on the growth, survival, and distribution of marine organisms, little is known regarding temperatures within coastal zones. Within coastal zones, seawater temperature varies as it is affected by a range of nearshore processes such as wave action, tides, and turbidity. Additionally, the thermal properties of the substratum may also affect temperature variation (Smale and Wernberg 2009), allowing for a large range in variation at a localized scale. Given the significance of the impacts of temperature, it is imperative to understand how marine organisms may respond to temperature variation at coastal regions on both a global and local scale.

The coastal region of South Africa, spanning approximately 3113 km in length (Smit et al. 2013), has not yet been studied in great detail at highly localized scales. Upon looking on a broad scale, this region exhibits a large variation in seawater temperatures across its coastline (Mead et al. 2013; Smit et al. 2013) and is divided into three distinct coastal regions, each with contrasting temperatures. These include the cold temperate west coast, warm temperate south coast, and the subtropical east coast. These regions display noticeable differences in seawater temperatures in comparison to each other, primarily due to the influences of the neighbouring ocean currents (Bolton et al. 2004; Mead et al. 2013; Schlegel and Smit 2016).

The South African coastline is bordered by the Benguela and Agulhas Currents on the west and east coasts respectively. The Benguela Current assists in transporting cold water northwards from the Southern Ocean (Hutchings et al. 2009; Schlegel et al. 2017), whereas the Agulhas, western boundary current, transports sub-tropical, warm water towards the tip of Africa (Smit et al. 2017). Together these two currents are responsible for the presence of a strong West-East thermal gradient occurring along the coastline of South Africa, with the west coast having significantly colder waters than the east coast. (Smit et al. 2013). The south coast is unique as it affected by both the Benguela and Agulhas currents. In this way, the south coast region differs from the other two coastal regions as it experiences greater variations within its localized thermal gradient due to the influences of two contrasting ocean currents (Lutjeharms and Ballegooyen 1988). These currents can vary up to as much as 10°C (Schlegel et al 2017) within a 24-hour period thus creating fluctuations in seawater temperatures around the Western Cape region. The Agulhas Current is driven by a wind stress curl between the southeast trade winds and the Southern Hemisphere westerlies (Beal et al. 2011). The Agulhas current retroreflects after making contact with the Benguela current and may often interact with the South Atlantic ( Hutchings et al., 2009), resulting in warm Indian Ocean water moving into the Atlantic at depths exceeding 2000m (Beal et al., 2011; Schlegel et al. 2017). These currents strongly affect the seawater temperatures around South Africa, and recent studies have shown that the temperatures have been changing. 

The statistical properties such as the mean, minimum, and maximum temperatures of in situ coastal seawater temperature time series representing the entire South African coastline, shows distinct coastal variations as a result of the Agulhas and Benguela currents (Schlegel and Smit 2016). Due to the small range of ambient temperatures experienced on the West coast, fluctuations are able to occur over a short period of time. Research has found that the seawater temperatures of the Benguela Current has been decreasing at a rate of approximately 0.5 °C per decade whilst the Agulhas Current has been increasing by between 0.55 °C - 0.7 °C per decade (Rouault et al. 2009; 2010). Overall, sea surface temperatures (SST) around South Africa have increased by approximately 0.25 °C between 1903 and 2013 (DEA, 2013) and are still increasing at a rate of 0.12 °C per decade (Schlegel and Smit, pers. comm.). The exact causes of these changes are not fully understood, however human activities are known to influence on coastal seawater temperature.

Due to their close proximity to populated or infrastructural areas, coastal regions are more accessible to humans in comparison to fully marine and open ocean regions. As a result, these areas are more susceptible to changes on both temporal and spatial scales(Help et al 2011; Kennish and Elliot 2011; Sink et al. 2012; Mead et al 2013). Along the South African coastline, direct pressures include exploitation of coastal resources, pollution and modification of communities (Griffiths et al 2004; Sink et al. 2012; Mead et al 2013). These changes may directly be influenced by anthropogenic activity and hence promote climate change which ultimately influences air temperature, wind and sea surface temperature (Mead and Robinson 2011; Rouault and Mead 2011; Mead et al 2013).

Over the last few decades, improvements in remote sensing technology have enabled researchers to map global sea surface temperature with a high level of accuracy (Zainuddin et al. 2006; Smale and Wernberg 2009). The National Oceanic and Atmospheric Administration’s (NOAA) series of satellites have provided global SST datasets from the 1980s on both global and local scales (Pearce et al. 2005). This data is critically important as satellite temperature datasets are often used to monitor changes in oceanic temperatures and provide valuable information on both biological and physical parameters in the ocean (Demarcq et al. 2010). Furthermore, satellite-derived SST data plays an important role in the creating projections predicting the potential effects of climate change on coastal and oceanic marine biota (Muller et al. 2009; Hilbish at al. 2011; Bartsch et al. 2012). Satellite-derived data is not as reliable as in situ temperature measurements, but are often used as a proxy when these measurements are scares or unavailable (Smale and Wernberg 2009). 

Developments of in situ collected coastal temperature data products over the last three decades provide a more reliable source of accurate coastal seawater temperature data (Smit et al. 2013). The South African Coastal Temperature Network (SACTN) has collected SST data for the South African coastline from as early as 1972, with contributions from various organisations and governmental departments. This data was obtained via a combination of different instruments and methods, including hand held alcohol thermometers and underwater temperature recorders, and as a result of this inconsistency, the coastal seawater temperature data has been recorded at differing levels of precision (0.5°C and 0.001°C respectively) but are likely more reliable than satellite derived data.

Satellite-derived temperature measurements often differ from in situ measurements (Katsaros 2003; Castillo and Lima 2010). This is primarily due to coastal satellite measurements failing to record small-scale variability or providing realistic information on average climatological temperatures. Smit et al. (2013) have shown that within offshore environments, satellite data generally reflects reality and has been validated against in situ measurements. Along coastal regions however, it was found that satellite-derived data had a warm bias of 6 °C when compared to coastal in situ collected seawater temperature data. For study sites located within a 400 m distance of the shoreline, it is recommended that data collected in situ be used over satellite-derived temperatures where possible (Smit et al. 2013).

 It is important to understand the characteristics of the data sources which aid in yielding accurate and reliable measurements when comparing temperature variation along the coast. This lead to the examination of of the 129 in situ collected sites which makes up the SACTN dataset. The length of the time series and statistical characteristics of the dataset was used to guide a series of analysis. The length of each time series for each of the sites were adjusted systematically hence forming the core of the analysis. The variation of each of the time series differ as expected, by the Agulhas and Benguela Currents. The purpose of this study was to examine variations in temperature between selected sites along the South African coastline using SST data in order to better understand patterns of coastal temperature at a localized scale. Additionally, this study also examined the influence of environmental factors, namely, wave action and exposure on coastal seawater temperatures. The aims of this study were to: i) examine whether there is homogeneity between the various sites sampled, ii) examine the driving factors that cause variation in coastal seawater temperatures along the South African coastline and iii) to examine whether the different instruments used in data collection varied in regards to the temperature values at the same sites.

\newpage
# Methods
## Wave and wind data

Wind, wave action, and exposure were important variables in this study as they exhibit a direct influence on coastal water temperatures, and were used to investigate the impact of abiotic parameters on seawater temperature at specific sites along the South African coast. Wind and wave data was obtained from the South African Weather Service (SAWS), and was presented at three hour resolutions. The data were then used to model short–crested waves generated by the wind into the coastal environment, using Simulating Waves in the Nearshore (SWAN). SWAN allows one to extract wave parameters from specific gridded locations in the nearshore. A resolution of 200 meters was modelled, at both seven meter and 15 meter contours. 

## Temperature data

To measure variances in temperature across sites, I used the SACTN dataset as my primary source of temperature data. This dataset consisted of coastal seawater temperatures for 129 sites along the coast of South Africa, measured daily from 1972 until 2017. Of these, 80 were measured using hand-held thermometers and the remaining 45 were measured using underwater temperature recorders (UTRs). Predominantly along the east coast of South Africa, data from those sites were collected using glass thermometers from boats at the shark net locations along the coastline at a precision of 0.1 °C. 

This dataset time series started from 1 January 1972 in Knysna, extending up to 20 December 2017 in Port Nolloth. Recordings per site are uneven, with the longest time series in the dataset being that of Gordons Bay which was recorded by SAWS. Data collected for this region started on the 13 September 1972 and ended on the 26 January 2017, with recordings still continuing daily. Within the 1970s, a total of 11 time series began recording. A further 53 entries were added during the 1980s, 34 entries were added during the 1990s, and 18 entries were added during the 2000s. Recordings are still ongoing at several of these sites. 

Seven sources contributed towards the compilation of this dataset: The Department of Environmental Affairs (DEA), South African Weather Services (SAWS), University of the Western Cape (UWC), Department of Forestry and Fisheries (DAFF), Kwa Zulu Natal Sharks Board (KZNSB), South African Environmental Observation Network (SAEON) and Ezemvelo KZN Wildlife Organization (EKZNW). KZNSB and SAWS made use of hand-held alcohol thermometers, and took measurements 20 cm below the sea surface. Temperature measurements taken with underwater temperature recorders, collected by DEA varied between a range of 0-28m, measurements obtained by DAFF varied between ranges of 0-9m, those collected by EKZN varied between ranges of 10-14m. SAEON and UWC placed the UTRs at depths of 0m and 0-6m respectively. Electronic instruments used for seawater temperature recordings have improved over the past four decades. Previous UTRs collected seawater temperature at a precision of 0.01°C whereas current models collect temperature at a thermal precision of 0.001°C. Data recorded using thermometers are saved and extracted annually. 

## Data storage

Data collection protocols varied amongst the seven sources contributing to the SATCN dataset.  As a result, the data was not uniformly formatted within the dataset. For my analyses, I combined and formatted all temperature data into standardized comma delineated values (CSV) which allowed for a fixed methodology to be used across the entire dataset, thereby improving accuracy. Prior to data analysis, I removed all data points exceeding 35 °C and/or below 0 °C as I considered these as outliers. These data points were then changed to NA (not available) so as to not interfere with analysis. All analysis performed in this thesis were conducted in R software version 3.4.2.

## Site selection

To compare temperatures along the South African coastline at a localized scale, I needed to select appropriate sites from each of the major coastal regions. Since temperature data was not evenly recorded for each of the 129 sites representing South Africa’s coastline, the first step was to narrow down available sites that could be adequately compared. To do this I performed a clustering analysis using the `kmeans` function in R software with multiple random seeds to identify a number of clustering solutions that grouped sites together based on their available temperature data. The mean, minimum, and maximum temperature values were used within the clustering to group sites with similar temperatures along each coastal region. The clustering analysis represented the most accurate and distinct site groupings based on temperature distributions and yielded distinct east, south, and west coast groupings and showed four clustering solutions along the South African coastline (Figure 1). With the data now divided into four distinct coastal regions, a time series was selected of at least one decade of data for each of the sites, excluding those with temperature data collected deeper than five meters. The length, decadal trend and precision of the time series were adjusted in a systematic manner to allow for meaningful comparisons to be made. 
 
```{r, echo= FALSE, message=FALSE, warning=FALSE, fig.cap="A map indicating the location of the 129 sites where temperatre measurements were collected along the South African coastline with the different coasts representing different colour variations.", fig.height=8, fig.width=12}

library(knitr)
load("data/southern_africa_coast.Rdata")

clust_i <- function(i) {
  set.seed(10)
ggplot(data = southern_africa_coast, aes(x = long, y = lat)) +
  geom_polygon(aes(group = group), fill = "grey70") +
    borders() +
    geom_point(data = site_list,
         aes(x = lon, y = lat, size = 1,
             colour = as.factor(kmeans(clust_columns, i)$cluster))) +
    labs(colour = "cluster")  +
    coord_equal(xlim = c(15, 35), ylim = c(-37, -27)) +
  annotate("text", label = "INDIAN\nOCEAN", x = 32.00, y = -34.0, size = 3.0, angle = 0, colour = "black") +
  annotate("text", label = "ATLANTIC\nOCEAN", x = 16.00, y = -34.0, size = 3.0, angle = 0, colour = "black") +
  geom_segment(aes(x = 17.2, y = -32.6, xend = 15.2, yend = -29.5),
                arrow = arrow(length = unit(0.3, "cm")), size = 0.1, colour = "black") +
    annotate("text", label = "Benguela", x = 16.0, y = -31.8, size = 3.5, angle = 298, colour = "black") +
    geom_segment(aes(x = 33, y = -29.5, xend = 29.8, yend = -33.0),
                arrow = arrow(length = unit(0.3, "cm")), size = 0.1, colour = "black") +
    annotate("text", label = "Agulhas", x = 31.7, y = -31.7, size = 3.5, angle = 53, colour = "black") +
  scale_x_continuous(breaks = seq(15, 35, 5),
                       labels = scales::unit_format("°E", sep = ""),
                       position = "bottom") +
    scale_y_continuous(breaks = seq(-35, -30, 5),
                       labels = c("35°S", "30°S")) +
    labs(x = NULL, y = NULL) +
    coord_cartesian(xlim = c(10.5, 39.5), ylim = c(-39.5, -25.5), expand = F) +
  theme_bw() +
    theme(panel.border = element_rect(fill = NA, colour = "black", size = 1),
          axis.text = element_text(colour = "black"),
          axis.ticks = element_line(colour = "black"))
}

clust_4 <- clust_i(4)
clust_4
```

Once sites were grouped together, the next step was to reduce the amount of sites down to a manageable, but still representative, sub-sample of the whole. This was done primarily for two reasons. The first, simply, is to allow for the comparisons to be more readily interpretable by humans. The second objective reason is to allow for equal amount of sampling per coast. The east is more heavily sampled than the rest and as such this imbalance must be addressed. The criteria considered for the sub-samples were that both instrument types were present and that data from as many different organizations possible were included. This process yielded four sites for each of the clusters along the South African coastline (Figure 2). The statistical characteristics of the temperature was used to guide analysis of the time series to produce an accurate assessment of temperature variation between sites that are grouped together. 

With each cluster having four sites I then used the haversine formula to calculate the geodesic distance between points specified by radians. Using this formula, I determined the distances (km) between each of the sites along the coastline. Thereafter, I matched sites within the same cluster based on the date that temperature was collected. This allows for a comparison to test whether or not temperature variation exists between sites within the same cluster. Once the sites were matched, I calculated means and standard deviations of temperatures between sites and clusters. This highlights the temperature variation between matched sites and allows for seasonal comparisons within the same cluster.

## Data analyses
I used a series of ANOVA tests to compare the main effects of my variables on a continuous variable. In this analysis I specifically analysed the relationship between matched sites based on the year and season as a function of the mean temperature. I used these analyses to test if significant differences occur between each pair of sites within each of the clusters. Once the temperature variation between sites were carefully analysed, I then compared the temperature data with the wave and wind data. Since the wave and wind data were collected at three hour resolutions, I first converted these into daily data points in order to compare it with the temperature data.

The wave data was collected at depths of 7 m or 15 m respectively. I used the ‘circular’ function in R software to create circular objects around the wave data to calculate the daily wave and wind direction. Thereafter I calculated the annual wave and wind direction for each of the sites. I then combined this to the temperature data for each site at the required time series where data was available. I then used the ‘s.window’ function in R to controls how rapidly the seasonal component of each variable varies, with small values allowing for rapid changes.


















