---
title: "Methods_writeup"
author: "Amieroh Abrahams"
date: "10 August 2018"
output: html_document
---

# Methods
## Wave and wind data

Wind, wave action, and exposure were important variables in this study as they exhibit a direct influence on coastal water temperatures, and were used to investigate the impact of abiotic parameters on seawater temperature at specific sites along the South African coast. Wind and wave data was obtained from the South African Weather Service (SAWS), and was presented at three hour resolutions. The data were then used to model short–crested waves generated by the wind into the coastal environment, using Simulating Waves in the Nearshore (SWAN). SWAN allows one to extract wave parameters from specific gridded locations in the nearshore. A resolution of 200 meters was modelled, at both seven meter and 15 meter contours. 

## Temperature data

To measure variances in temperature across sites, I used the SACTN dataset as my primary source of temperature data. This dataset consisted of coastal seawater temperatures for 129 sites along the coast of South Africa, measured daily from 1972 until 2017. Of these, 80 were measured using hand-held thermometers and the remaining 45 were measured using underwater temperature recorders (UTRs). Predominantly along the east coast of South Africa, data from those sites were collected using glass thermometers from boats at the shark net locations along the coastline at a precision of 0.1 °C. 

This dataset time series started from 1 January 1972 in Knysna, extending up to 20 December 2017 in Port Nolloth. Recordings per site are uneven, with the longest time series in the dataset being that of Gordons Bay which was recorded by SAWS. Data collected for this region started on the 13 September 1972 and ended on the 26 January 2017, with recordings still continuing daily. Within the 1970s, a total of 11 time series began recording. A further 53 entries were added during the 1980s, 34 entries were added during the 1990s, and 18 entries were added during the 2000s. Recordings are still ongoing at several of these sites. 

Seven sources contributed towards the compilation of this dataset: The Department of Environmental Affairs (DEA), South African Weather Services (SAWS), University of the Western Cape (UWC), Department of Forestry and Fisheries (DAFF), Kwa Zulu Natal Sharks Board (KZNSB), South African Environmental Observation Network (SAEON) and Ezemvelo KZN Wildlife Organization (EKZNW). KZNSB and SAWS made use of hand-held alcohol thermometers, and took measurements 20 cm below the sea surface. DEA, DAFF, SAEON, UWC and EKZN used UTRs to obtain seawater temperature recordings at each of the sites. Electronic instruments used for seawater temperature recordings have improved over the past four decades. Previous UTRs collected seawater temperature at a precision of 0.01°C whereas current models collect temperature at a thermal precision of 0.001°C. Data recorded using thermometers are saved and extracted annually. 

## Data storage

Data collection protocols varied amongst the seven sources contributing to the SATCN dataset.  As a result, the data was not uniformly formatted within the dataset. For my analyses, I combined and formatted all temperature data into standardized comma delineated values (CSV) which allowed for a fixed methodology to be used across the entire dataset, thereby improving accuracy. Prior to data analysis, I removed all data points exceeding 35 °C and/or below 0 °C as I considered these as outliers. These data points were then changed to NA (not available) so as to not interfere with analysis. All analysis performed in this thesis were conducted in R software version 3.4.2.

## Site selection

To compare temperatures along the South African coastline at a localized scale, I needed to select appropriate sites from each of the major coastal regions. Since temperature data was not evenly recorded for each of the 129 sites representing South Africa’s coastline, the first step was to narrow down available sites that could be adequately compared. To do this I performed a clustering analysis using the `kmeans` function in R software with multiple random seeds to identify a number of clustering solutions that grouped sites together based on their available temperature data. The mean, minimum, and maximum temperature values were used within the clustering to group sites with similar temperatures along each coastal region. The clustering analysis represented the most accurate and distinct site groupings based on temperature distributions and yielded distinct east, south, and west coast groupings and showed four clustering solutions along the South African coastline (Figure 1). With the data now divided into four distinct coastal regions, a time series was selected of at least one decade of data for each of the sites, excluding those with temperature data collected deeper than five meters. The length, decadal trend and precision of the time series were adjusted in a systematic manner to allow for meaningful comparisons to be made. 

```{r, echo= FALSE, message=FALSE, warning=FALSE, fig.cap="A map indicating the location of the 129 sites where temperatre measurements were collected along the South African coastline with the different coasts representing different colour variations.", fig.height=8, fig.width=12}

library(knitr)
load("data/southern_africa_coast.Rdata")

clust_i <- function(i) {
  set.seed(10)
ggplot(data = southern_africa_coast, aes(x = long, y = lat)) +
  geom_polygon(aes(group = group), fill = "grey70") +
    borders() +
    geom_point(data = site_list,
         aes(x = lon, y = lat, size = 1,
             colour = as.factor(kmeans(clust_columns, i)$cluster))) +
    labs(colour = "cluster")  +
    coord_equal(xlim = c(15, 35), ylim = c(-37, -27)) +
  annotate("text", label = "INDIAN\nOCEAN", x = 32.00, y = -34.0, size = 3.0, angle = 0, colour = "black") +
  annotate("text", label = "ATLANTIC\nOCEAN", x = 16.00, y = -34.0, size = 3.0, angle = 0, colour = "black") +
  geom_segment(aes(x = 17.2, y = -32.6, xend = 15.2, yend = -29.5),
                arrow = arrow(length = unit(0.3, "cm")), size = 0.1, colour = "black") +
    annotate("text", label = "Benguela", x = 16.0, y = -31.8, size = 3.5, angle = 298, colour = "black") +
    geom_segment(aes(x = 33, y = -29.5, xend = 29.8, yend = -33.0),
                arrow = arrow(length = unit(0.3, "cm")), size = 0.1, colour = "black") +
    annotate("text", label = "Agulhas", x = 31.7, y = -31.7, size = 3.5, angle = 53, colour = "black") +
  scale_x_continuous(breaks = seq(15, 35, 5),
                       labels = scales::unit_format("°E", sep = ""),
                       position = "bottom") +
    scale_y_continuous(breaks = seq(-35, -30, 5),
                       labels = c("35°S", "30°S")) +
    labs(x = NULL, y = NULL) +
    coord_cartesian(xlim = c(10.5, 39.5), ylim = c(-39.5, -25.5), expand = F) +
  theme_bw() +
    theme(panel.border = element_rect(fill = NA, colour = "black", size = 1),
          axis.text = element_text(colour = "black"),
          axis.ticks = element_line(colour = "black"))
}

clust_4 <- clust_i(4)
clust_4
```

Once sites were grouped together, the next step was to reduce the amount of sites down to a manageable, but still representative, sub-sample of the whole. This was done primarily for two reasons. The first, simply, is to allow for the comparisons to be more readily interpretable by humans. The second objective reason is to allow for equal amount of sampling per coast. The east is more heavily sampled than the rest and as such this imbalance must be addressed. The criteria considered for the sub-samples were that both instrument types were present and that data from as many different organizations possible were included. This process yielded four sites for each of the clusters along the South African coastline (Figure 2). The statistical characteristics of the temperature was used to guide analysis of the time series to produce an accurate assessment of temperature variation between sites that are grouped together. 

With each cluster having four sites I then used the haversine formula to calculate the geodesic distance between points specified by radians. Using this formula, I determined the distances (km) between each of the sites along the coastline. Thereafter, I matched sites within the same cluster based on the date that temperature was collected. This allows for a comparison to test whether or not temperature variation exists between sites within the same cluster. Once the sites were matched, I calculated means and standard deviations of temperatures between sites and clusters. This highlights the temperature variation between matched sites and allows for seasonal comparisons within the same cluster.

## Data analyses
I used a series of ANOVA tests to compare the main effects of my variables on a continuous variable. In this analysis I specifically analysed the relationship between matched sites based on the year and season as a function of the mean temperature. I used these analyses to test if significant differences occur between each pair of sites within each of the clusters. Once the temperature variation between sites were carefully analysed, I then compared the temperature data with the wave and wind data. Since the wave and wind data were collected at three hour resolutions, I first converted these into daily data points in order to compare it with the temperature data.

The wave data was collected at depths of 7 m or 15 m respectively. I used the ‘circular’ function in R software to create circular objects around the wave data to calculate the daily wave and wind direction. Thereafter I calculated the annual wave and wind direction for each of the sites. I then combined this to the temperature data for each site at the required time series where data was available. I then used the ‘s.window’ function in R to controls how rapidly the seasonal component of each variable varies, with small values allowing for rapid changes.









































