---
title: "Introduction"
author: "Amieroh Abrahams"
date: "3 July 2018"
output: html_document
  word_document:
    toc: yes
  html_document:
    fig_caption: yes
    fig_height: 5
    fig_width: 5
    highlight: default
    number_sections: yes
    theme: paper
    toc: yes
    toc_float: yes
  pdf_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 6
    highlight: zenburn
    latex_engine: xelatex
mainfont: PT Serif
monofont: PT Mono
language: Australian
sansfont: PT Sans
fontsize: 12pt
---

# Introduction

Temperature is the main determinant of biogeographical patterns and ecosystem processes, having observable effects on an organism’s survival and reproductive patterns (Smit et al. 2013). The temperatures of seawater are a key indicator of environmental changes in marine ecosystems (Pearce et al. 2006). Despite the controlling effects that temperature plays on the growth, survival, and distribution of marine organisms, little is known regarding temperatures within coastal zones. Within coastal zones, seawater temperature varies as it is affected by a range of nearshore processes such as wave action, tides, and turbidity. Additionally, the thermal properties of the substratum may also affect temperature variation (Smale and Wernberg 2009), allowing for a large range in variation at a localized scale. Given the significance of the impacts of temperature, it is imperative to understand how marine organisms may respond to temperature variation at coastal regions on both a global and local scale.

The coastal region of South Africa, spanning approximately 3113 km in length (Smit et al. 2013), has not yet been studied in great detail at highly localized scales. Upon looking on a broad scale, this region exhibits a large variation in seawater temperatures across its coastline (Mead et al. 2013; Smit et al. 2013) and is divided into three distinct coastal regions, each with contrasting temperatures. These include the cold temperate west coast, warm temperate south coast, and the subtropical east coast. These regions display noticeable differences in seawater temperatures in comparison to each other, primarily due to the influences of the neighbouring ocean currents (Bolton et al. 2004; Mead et al. 2013; Schlegel and Smit 2016).

The South African coastline is bordered by the Benguela and Agulhas Currents on the west and east coasts respectively. The Benguela Current assists in transporting cold water northwards from the Southern Ocean (Hutchings et al. 2009; Schlegel et al. 2017), whereas the Agulhas, western boundary current, transports sub-tropical, warm water towards the tip of Africa (Smit et al. 2017). Together these two currents are responsible for the presence of a strong West-East thermal gradient occurring along the coastline of South Africa, with the west coast having significantly colder waters than the east coast. (Smit et al. 2013). The south coast is unique as it affected by both the Benguela and Agulhas currents. In this way, the south coast region differs from the other two coastal regions as it experiences greater variations within its localized thermal gradient due to the influences of two contrasting ocean currents (Lutjeharms and Ballegooyen 1988). These currents can vary up to as much as 10°C (Schlegel et al 2017) within a 24-hour period thus creating fluctuations in seawater temperatures around the Western Cape region. The Agulhas Current is driven by a wind stress curl between the southeast trade winds and the Southern Hemisphere westerlies (Beal et al. 2011). The Agulhas current retroreflects after making contact with the Benguela current and may often interact with the South Atlantic ( Hutchings et al., 2009), resulting in warm Indian Ocean water moving into the Atlantic at depths exceeding 2000m (Beal et al., 2011; Schlegel et al. 2017). These currents strongly affect the seawater temperatures around South Africa, and recent studies have shown that the temperatures have been changing. 

The statistical properties such as the mean, minimum, and maximum temperatures of in situ coastal seawater temperature time series representing the entire South African coastline, shows distinct coastal variations as a result of the Agulhas and Benguela currents (Schlegel and Smit 2016). Due to the small range of ambient temperatures experienced on the West coast, fluctuations are able to occur over a short period of time. Research has found that the seawater temperatures of the Benguela Current has been decreasing at a rate of approximately 0.5 °C per decade whilst the Agulhas Current has been increasing by between 0.55 °C - 0.7 °C per decade (Rouault et al. 2009; 2010). Overall, sea surface temperatures (SST) around South Africa have increased by approximately 0.25 °C between 1903 and 2013 (DEA, 2013) and are still increasing at a rate of 0.12 °C per decade (Schlegel and Smit, pers. comm.). The exact causes of these changes are not fully understood, however human activities are known to influence on coastal seawater temperature.

Due to their close proximity to populated or infrastructural areas, coastal regions are more accessible to humans in comparison to fully marine and open ocean regions. As a result, these areas are more susceptible to changes on both temporal and spatial scales(Help et al 2011; Kennish and Elliot 2011; Sink et al. 2012; Mead et al 2013). Along the South African coastline, direct pressures include exploitation of coastal resources, pollution and modification of communities (Griffiths et al 2004; Sink et al. 2012; Mead et al 2013). These changes may directly be influenced by anthropogenic activity and hence promote climate change which ultimately influences air temperature, wind and sea surface temperature (Mead and Robinson 2011; Rouault and Mead 2011; Mead et al 2013).

Over the last few decades, improvements in remote sensing technology have enabled researchers to map global sea surface temperature with a high level of accuracy (Zainuddin et al. 2006; Smale and Wernberg 2009). The National Oceanic and Atmospheric Administration’s (NOAA) series of satellites have provided global SST datasets from the 1980s on both global and local scales (Pearce et al. 2005). This data is critically important as satellite temperature datasets are often used to monitor changes in oceanic temperatures and provide valuable information on both biological and physical parameters in the ocean (Demarcq et al. 2010). Furthermore, satellite-derived SST data plays an important role in the creating projections predicting the potential effects of climate change on coastal and oceanic marine biota (Muller et al. 2009; Hilbish at al. 2011; Bartsch et al. 2012). Satellite-derived data is not as reliable as in situ temperature measurements, but are often used as a proxy when these measurements are scares or unavailable (Smale and Wernberg 2009). 

Developments of in situ collected coastal temperature data products over the last three decades provide a more reliable source of accurate coastal seawater temperature data (Smit et al. 2013). The South African Coastal Temperature Network (SACTN) has collected SST data for the South African coastline from as early as 1972, with contributions from various organisations and governmental departments. This data was obtained via a combination of different instruments and methods, including hand held alcohol thermometers and underwater temperature recorders, and as a result of this inconsistency, the coastal seawater temperature data has been recorded at differing levels of precision (0.5°C and 0.001°C respectively) but are likely more reliable than satellite derived data.

Satellite-derived temperature measurements often differ from in situ measurements (Katsaros 2003; Castillo and Lima 2010). This is primarily due to coastal satellite measurements failing to record small-scale variability or providing realistic information on average climatological temperatures. Smit et al. (2013) have shown that within offshore environments, satellite data generally reflects reality and has been validated against in situ measurements. Along coastal regions however, it was found that satellite-derived data had a warm bias of 6 °C when compared to coastal in situ collected seawater temperature data. For study sites located within a 400 m distance of the shoreline, it is recommended that data collected in situ be used over satellite-derived temperatures where possible (Smit et al. 2013).

 It is important to understand the characteristics of the data sources which aid in yielding accurate and reliable measurements when comparing temperature variation along the coast. This lead to the examination of of the 129 in situ collected sites which makes up the SACTN dataset. The length of the time series and statistical characteristics of the dataset was used to guide a series of analysis. The length of each time series for each of the sites were adjusted systematically hence forming the core of the analysis. The variation of each of the time series differ as expected, by the Agulhas and Benguela Currents. The purpose of this study was to examine variations in temperature between selected sites along the South African coastline using SST data in order to better understand patterns of coastal temperature at a localized scale. Additionally, this study also examined the influence of environmental factors, namely, wave action and exposure on coastal seawater temperatures. The aims of this study were to: i) examine whether there is homogeneity between the various sites sampled, ii) examine the driving factors that cause variation in coastal seawater temperatures along the South African coastline and iii) to examine whether the different instruments used in data collection varied in regards to the temperature values at the same sites.